### PR TITLE
add owners

### PR DESCRIPTION
**Pull request by ldpliu**

### CODE REVIEW

**Comment by KevinFCormier** [comment]
@ldpliu This repository is not Prow-enabled, so the OWNERS file is not really serving any purpose at the moment. Are you looking to contribute something? (There is more focus on implementing new features in https://github.com/open-cluster-management/cm-cli currently.)

**Comment by ldpliu** [comment]
> @ldpliu This repository is not Prow-enabled, so the OWNERS file is not really serving any purpose at the moment. Are you looking to contribute something? (There is more focus on implementing new features in https://github.com/open-cluster-management/cm-cli currently.)

OK, thank you.
We are just working on CLC repo skill transfer, so assign each member some repos, and we need to add us to owners file.
https://docs.google.com/spreadsheets/d/1oh204BdZdtzU7_MZ7mGsFidQXrpN3befZMvpLbXf2Lg/edit#gid=0

**Comment by KevinFCormier** [comment]
@ldpliu Thanks. This repo isn't really part of CLC. It's a CLI I created to help teams coordinate their usage of ClusterPools for cost management.

**Comment by ldpliu** [comment]
> @ldpliu Thanks. This repo isn't really part of CLC. It's a CLI I created to help teams coordinate their usage of ClusterPools for cost management.

ok, thank you

**Pull request closed without merging**
